# Generated by Django 3.1.1 on 2020-09-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_auto_20200918_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
