# Generated by Django 3.1.1 on 2020-09-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_model_a_model_b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_A',
        ),
        migrations.DeleteModel(
            name='Model_B',
        ),
    ]
