# Generated by Django 3.1.1 on 2020-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_auto_20200920_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
