# Generated by Django 3.1.1 on 2020-09-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_auto_20200921_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.pedido'),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.producto'),
        ),
    ]
