# Generated by Django 3.1.1 on 2020-09-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0009_invoices_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='producto',
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
